sudo: false
language: rust
rust: nightly
script:
  - cargo build
  - cargo test
  - cargo doc
after_success: curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh