sudo: false
branches:
  except:
      - servo

language: rust
script: scripts/travis-build.sh
after_success: curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh
