[package]
name = "xml5ever"
version = "0.2.0"
description = "Push based streaming parser for xml"
homepage = "https://github.com/Ygg01/xml5ever/blob/master/README.md"
documentation = "https://ygg01.github.io/docs/xml5ever/xml5ever/index.html"
repository = "https://github.com/Ygg01/xml5ever"
readme = "README.md"
keywords = ["xml", "xml5", "parser", "parsing"]
authors = ["The xml5ever project developers"]
license = "MIT / Apache-2.0"
build = "build.rs"
exclude = ["xml5lib-tests/*"]

[features]
unstable = ["tendril/unstable"]

[dependencies]
time = "0"
log = "0"
phf = "0.7"
mac = "0"
tendril = "0.2"
html5ever-atoms = "0.1"

[dev-dependencies]
rustc-serialize = "0.3.15"

[build-dependencies]
phf_codegen = "0.7.3"
rustc-serialize = "0.3.15"

[profile.dev]
debug = false

[profile.test]
debug = false
