[package]
name = "xml5ever"
version = "0.1.0"
authors = ["Daniel Fath <daniel.fath7@gmail.com>"]
license = "MIT / Apache-2.0"
build = "build.rs"

[features]
unstable = ["tendril/unstable", "string_cache/unstable", "string_cache_plugin", "rc/unstable"]

[dependencies]
time = "0"
log = "0"
string_cache = "0.1.7"
phf = "0.7"
string_cache_plugin = { version = "0.1.5", optional = true }
mac = "0"
tendril = "0.1.3"
rc = "0.1.1"

[dev-dependencies]
rustc-serialize = "0.3.15"

[build-dependencies]
phf_codegen = "0.7.3"
rustc-serialize = "0.3.15"

[profile.dev]
debug = false

[profile.test]
debug = false
