[package]

name = "xml5ever"
version = "0.5.0"
authors = ["The xml5ever project developers"]
license = "MIT / Apache-2.0"
repository = "https://github.com/servo/html5ever"
description = "Push based streaming parser for xml"
documentation = "https://docs.rs/xml5ever/"
build = "build.rs"

homepage = "https://github.com/servo/html5ever/blob/master/xml5ever/README.md"
readme = "README.md"
keywords = ["xml", "xml5", "parser", "parsing"]
exclude = ["xml5lib-tests/*"]

[lib]
name = "xml5ever"

# https://github.com/rust-lang/cargo/issues/1512
doctest = false

[features]
unstable = ["tendril/unstable"]

[dependencies]
time = "0.1"
log = "0.3"
phf = "0.7"
mac = "0.1"
tendril = "0.2"
html5ever-atoms = {version = "0.3", path = "../atoms" }

[dev-dependencies]
rustc-serialize = "0.3.15"
rustc-test = "0.1.3"

[build-dependencies]
phf_codegen = "0.7"
rustc-serialize = "0.3.15"
