name: CI

on:
  push:
    branches: [auto]
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.56.0, stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2

      - name: Set toolchain
        run: |
          rustup set profile minimal
          rustup override set ${{ matrix.version }}

      - name: Init submodules
        run: git submodule update --init

      - name: Cargo bench
        if: matrix.version != '1.41.0'
        run: cargo bench --all
        env:
          RUSTFLAGS: --cfg bench

      - name: Test "rustc-test/capture" feature
        if: matrix.version == 'nightly'
        working-directory: rcdom
        run: cargo test --features "rustc-test/capture"

      - name: Cargo test
        if: matrix.version != 'nightly'
        run: cargo test --all

      - name: Cargo doc
        if: matrix.version == 'nightly'
        run: cargo doc

  build_result:
    name: homu build finished
    runs-on: ubuntu-latest
    needs:
      - "ci"

    steps:
      - name: Mark the job as successful
        run: exit 0
        if: success()
      - name: Mark the job as unsuccessful
        run: exit 1
        if: "!success()"
